version: '3.8'

services:
  nginx-proxy:
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile
    restart: always
    image: danydodson/nginx-proxy
    ports:
      - 80:8081
    volumes:
      - './nginx-proxy/data:/etc/nginx'
      - './nginx-proxy/lua:/usr/local/openresty/nginx/lua'
    networks:
      - front-tier
      - back-tier
    depends_on:
      - users-service

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    restart: always
    image: danydodson/web-client
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8081
    stdin_open: true
    volumes:
      - './web-client:/usr/src/app'
      - 'pwa-nm:/usr/src/app/node_modules'
    networks:
      - front-tier
    depends_on:
      - users-service

  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    restart: always
    image: danydodson/users-service
    volumes:
      - './users-service:/usr/src/app'
      - 'users-nm:/usr/src/app/node_modules'
    environment:
      NODE_ENV: development
    ports:
      - 3100:3100
      - 9229:9229
    command: npm run debug
    networks:
      - back-tier

networks:
  front-tier:
  back-tier:

volumes:
  pwa-nm: null
  users-nm: null
